apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-test
  namespace: my-ingress-namespace
spec:
  ingressClassName: nginx   # this tell K8s which controller should handle this Ingress
  rules:
    - host: ingress.hostbase.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: springboot-service-for-k8s
                port:
                  number: 80
          - path: /common-api
            pathType: Prefix
            backend:
              service:
                name: ingress-nginx-service
                port:
                  number: 91